variable "project_id" {
  description = "The Google Cloud Project ID where the policy will be applied."
  type        = string
}

variable "allowed_models" {
  description = "List of allowed Vertex AI models (e.g., ['publishers/google/models/gemini-pro:predict']). Generated by enumerate.py."
  type        = list(string)
}
